drop database if exists schools_data;
create database schools_data;

\c schools_data

drop table if exists schools;
create table schools(
  natemis                      varchar(15) not null ,
  datayear                     int                  ,
  province                     char(2)              ,
  province_cd                  int                  ,
  institution_name             varchar(100)         ,
  status                       varchar(30)          ,
  sector                       varchar(30)          ,
  type_ped                     varchar(30)          ,
  phase_ped                    varchar(30)          ,
  specialization               varchar(100)         ,
  owner_land                   varchar(30)          ,
  owner_buildings              varchar(30)          ,
  ex_dept                      varchar(50)          ,
  paypoint_no                  varchar(30)          ,
  component_no                 varchar(30)          ,
  exam_no                      varchar(30)          ,
  exam_center                  varchar(100)         ,
  new_lat                      decimal(12,7)        ,
  new_long                     decimal(12,7)        ,
  gis_source                   varchar(50)          ,
  district_municipality_name   varchar(100)         ,
  local_municipality_name      varchar(100)         ,
  ward_id                      int                  ,
  sp_code                      int                  ,
  sp_name                      varchar(30)          ,
  ei_district                  varchar(50)          ,
  ei_circuit                   varchar(30)          ,
  addressee                    varchar(100)         ,
  township_village             varchar(100)         ,
  suburb                       varchar(100)         ,
  town_city                    varchar(100)         ,
  street_address               varchar(200)         ,
  postal_address               varchar(200)         ,
  telephone                    varchar(20)          ,
  section_21                   varchar(30)          ,
  section_21_function          varchar(30)          ,
  quintile                     varchar(100)         ,
  nas                          varchar(20)          ,
  nodal_area                   varchar(20)          ,
  registration_date            varchar(20)          ,
  no_fee_school                varchar(100)         ,
  allocation                   int                  ,
  demarcation_from             varchar(20)          ,
  demarcation_to               varchar(20)          ,
  old_natemis                  varchar(15)          ,
  new_natemis                  varchar(15)          ,
  learners                     int                  ,
  educators                    int                  ,
  primary key(natemis)
);